let modelRequest=0,onlineModels=[];
const API_BASE=window.LOOM_API_BASE||'';
const providers={
 DeepSeek:{url:'https://api.deepseek.com/v1',models:['deepseek-chat','deepseek-reasoner']},
 '智谱 GLM':{url:'https://open.bigmodel.cn/api/paas/v4',models:['glm-4.5','glm-4.5-air','glm-4-plus']},
 '阿里云 · 千问':{url:'https://dashscope.aliyuncs.com/compatible-mode/v1',models:['qwen-plus','qwen-max','qwen-turbo','qwen3-max']},
 OpenAI:{url:'https://api.openai.com/v1',models:['gpt-4.1','gpt-4.1-mini','o3','o4-mini']},
 'Anthropic · Claude':{url:'https://api.anthropic.com/v1',models:['claude-sonnet-4-5','claude-opus-4-1'],protocol:'anthropic'},
 'Google · Gemini':{url:'https://generativelanguage.googleapis.com/v1beta/openai',models:['gemini-2.5-pro','gemini-2.5-flash']},
 '月之暗面 · Kimi':{url:'https://api.moonshot.cn/v1',models:['kimi-k2-0905-preview','moonshot-v1-128k']},
 '字节跳动 · 豆包':{url:'https://ark.cn-beijing.volces.com/api/v3',models:['doubao-seed-1-6-250615'],note:'也可填入火山引擎控制台的推理接入点 ID（ep-…）。'},
 MiniMax:{url:'https://api.minimax.io/v1',models:['MiniMax-M2.7','MiniMax-M2.5']},
 'xAI · Grok':{url:'https://api.x.ai/v1',models:['grok-4','grok-3-mini']},
 Mistral:{url:'https://api.mistral.ai/v1',models:['mistral-large-latest','mistral-small-latest']},
 '硅基流动':{url:'https://api.siliconflow.cn/v1',models:['deepseek-ai/DeepSeek-V3','Qwen/Qwen3-235B-A22B']},
 OpenRouter:{url:'https://openrouter.ai/api/v1',models:['anthropic/claude-sonnet-4.5','google/gemini-2.5-pro','deepseek/deepseek-chat']},
 Groq:{url:'https://api.groq.com/openai/v1',models:['llama-3.3-70b-versatile','openai/gpt-oss-120b']},
 'Together AI':{url:'https://api.together.xyz/v1',models:['meta-llama/Llama-3.3-70B-Instruct-Turbo']},
 '自定义服务':{url:'',models:[''],note:'支持 OpenAI 兼容的 Chat Completions 接口。'}
};
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let uid=0,round=0,quotes=[];function makeCol(p){return {id:++uid,provider:p,model:providers[p].models[0],endpoint:providers[p].url,protocol:providers[p].protocol||'openai',key:'',history:[],busy:false}}
let cols=['DeepSeek','智谱 GLM','阿里云 · 千问'].map(makeCol);
const STORAGE_KEY='loom.workspace.v1';let sessions=[],currentId='',storageBlocked=false;
const clone=value=>JSON.parse(JSON.stringify(value));
function storageError(text){$('storage-warning').hidden=false;$('storage-warning').textContent=text;}
function newId(){return Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)}
function snapshot(){const first=cols.flatMap(c=>c.history).find(m=>m.role==='user');return {id:currentId,title:first?.display||first?.content||'新对话',updated:Date.now(),round,cols:clone(cols),quotes:quotes.map(({message,...q})=>q),draft:$('prompt').value,highlight:$('highlight').checked};}
function persist(){if(storageBlocked)return;const session=snapshot();const index=sessions.findIndex(x=>x.id===currentId);if(index<0)sessions.push(session);else sessions[index]=session;try{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,uid,currentId,sessions}));$('storage-warning').hidden=true;}catch{storageError('浏览器未能保存：存储空间不足或本地存储不可用。当前内容仍可使用，但刷新前请保留重要内容。');}}
function restore(session){currentId=session.id;cols=clone(session.cols);round=session.round||0;quotes=clone(session.quotes||[]);$('prompt').value=session.draft||'';$('highlight').checked=session.highlight!==false;cols.forEach(c=>{if(c.busy){const last=c.history.at(-1);if(last?.role==='user')c.history.push({role:'assistant',content:'上次请求因页面关闭或刷新而中断，请重新发送。',round:last.round,error:true});}c.busy=false;});uid=Math.max(uid,...cols.map(c=>c.id),...quotes.map(q=>q.id));}
function loadWorkspace(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const state=JSON.parse(raw);if(state.version!==1||!Array.isArray(state.sessions)||!state.sessions.length||state.sessions.some(s=>!s.id||!Array.isArray(s.cols)||s.cols.length<1||s.cols.length>5||s.cols.some(c=>!providers[c.provider]||!Number.isFinite(c.id)||!Array.isArray(c.history))))throw Error('invalid');sessions=state.sessions;uid=Number.isFinite(state.uid)?state.uid:uid;restore(sessions.find(s=>s.id===state.currentId)||sessions[0]);return}}catch{storageBlocked=true;storageError('无法读取本地记录，原始存储已保留。本次修改暂不写入，请检查浏览器的存储设置。');}currentId=newId();}
function showHistory(){if(working())return;persist();$('history-search').value='';renderHistory();$('history-dialog').showModal();}
function renderHistory(){const query=$('history-search').value.trim().toLowerCase();const list=[...sessions].sort((a,b)=>b.updated-a.updated).filter(s=>!query||s.title.toLowerCase().includes(query)||s.cols.some(c=>c.history.some(m=>m.content.toLowerCase().includes(query))));$('history-list').innerHTML=list.map(s=>`<button class="history-item ${s.id===currentId?'selected':''}" data-session="${esc(s.id)}"><span class="history-item-title">${esc(s.title.slice(0,80))}</span><span class="history-item-meta">${new Date(s.updated).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})} · ${s.round} 轮 · ${s.cols.length} 个模型 ${s.id===currentId?' · 当前对话':''}</span></button>`).join('')||'<div class="history-empty">没有找到相关对话</div>';document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>switchSession(b.dataset.session));}
function switchSession(id){if(working()||id===currentId){$('history-dialog').close();return}const target=sessions.find(s=>s.id===id);if(!target)return;persist();restore(target);$('history-dialog').close();renderQuotes();render({latest:true});}
loadWorkspace();
try{document.body.classList.toggle('sidebar-collapsed',localStorage.getItem('loom.sidebar.collapsed')==='true')}catch{}
function syncSidebar(){const collapsed=document.body.classList.contains('sidebar-collapsed');$('sidebar-toggle').textContent=collapsed?'›':'‹';$('sidebar-toggle').setAttribute('aria-expanded',String(!collapsed));$('sidebar-toggle').setAttribute('aria-label',collapsed?'展开侧边栏':'收起侧边栏');$('sidebar-toggle').title=collapsed?'展开侧边栏':'收起侧边栏'}
syncSidebar();$('sidebar-toggle').onclick=()=>{document.body.classList.toggle('sidebar-collapsed');syncSidebar();try{localStorage.setItem('loom.sidebar.collapsed',String(document.body.classList.contains('sidebar-collapsed')))}catch{}};

const complete=c=>!!(c.key&&c.model&&c.endpoint),working=()=>cols.some(c=>c.busy);
function markdown(text){return DOMPurify.sanitize(marked.parse(text,{gfm:true,breaks:true}),{ALLOWED_TAGS:['p','br','h1','h2','h3','h4','h5','h6','strong','em','del','s','ul','ol','li','blockquote','pre','code','table','thead','tbody','tr','th','td','hr','a'],ALLOWED_ATTR:['href','title','start']});}
function render({latest=false}={}){
 const positions=new Map([...document.querySelectorAll('.messages')].map(el=>[+el.dataset.col,el.scrollTop]));
 $('board').style.gridTemplateColumns=`repeat(${cols.length},minmax(260px,1fr))`;
 $('board').innerHTML=cols.map((c,i)=>{
 const rounds=c.history.filter(m=>m.role==='user');return `<article class="column" data-id="${c.id}"><div class="colhead"><div class="model"><span class="icon color${i%5}">${['D','G','Q','A','M'][i%5]}</span><div><strong>${esc(c.provider)}</strong><div class="model-sub">${esc(c.model||'选择型号')}</div></div></div><button class="iconbtn config" data-i="${i}" title="修改本列模型" aria-label="修改第 ${i+1} 列模型">⌘</button></div><div class="col-status"><span class="dot ${complete(c)?'ready':''}"></span>${c.busy?'正在生成回答…':complete(c)?'模型配置成功':'尚未连接'}<span>${rounds.length} 轮对话</span></div><div class="conversation"><nav class="roundnav" aria-label="${esc(c.provider)} 轮次导航"><div class="navscroll">${rounds.map(m=>`<button class="round-link" data-col="${c.id}" data-round="${m.round}" aria-label="第 ${m.round} 轮：${esc(m.title)}"><i></i><span class="round-tooltip">第 ${m.round} 轮 · ${esc(m.title)}</span></button>`).join('')}</div></nav><div class="messages" data-col="${c.id}">${c.history.length?c.history.map((m,j)=>`<section class="msg ${m.role==='user'?'question':'response'}" ${m.role==='user'?`id="round-${c.id}-${m.round}"`:''}><div class="label">${m.role==='user'?`<span>你</span><small>第 ${m.round} 轮</small>`:`<span>${esc(c.provider)}</span><small>${m.error?'请求未完成':'回答'}</small>`}</div><div class="${m.role==='user'?'user':'answer markdown'} ${m.error?'error':''}" data-message="${j}">${m.role==='user'?esc(m.display||m.content):m.error?esc(m.content):markdown(m.content)}</div>${m.refs?.length?`<details class="ref-detail"><summary>引用 ${m.refs.length} 个高亮片段</summary>${m.refs.map(q=>`<p><b>${esc(q.source)}</b> ${esc(q.text)}</p>`).join('')}</details>`:''}</section>`).join('')+(c.busy?'<div class="thinking"><i></i><i></i><i></i><span>模型正在思考</span></div>':''):`<div class="empty"><div class="empty-symbol">✳</div><strong>${complete(c)?'准备好，开始思考':'连接你的模型'}</strong><p>${complete(c)?'在下方提出问题，<br>让不同模型一起寻找答案。':'选择你喜欢的模型，填入 API Key。<br>同一个问题，获得独立的思考。'}</p>${complete(c)?'<span class="connected-pill">✓ 模型配置成功</span>':`<button class="btn config" data-i="${i}">配置本列模型 <span>↗</span></button>`}</div>`}</div></div></article>`;
 }).join('');
 document.querySelectorAll('.config').forEach(b=>{b.disabled=working();b.onclick=()=>openConfig(+b.dataset.i)});
 document.querySelectorAll('.messages').forEach(el=>{el.scrollTop=positions.get(+el.dataset.col)||0;if(latest===true||(Array.isArray(latest)&&latest.includes(+el.dataset.col))){const question=[...el.querySelectorAll('.question')].at(-1);if(question)el.scrollTop=Math.max(0,el.scrollTop+question.getBoundingClientRect().top-el.getBoundingClientRect().top-20);}el.addEventListener('scroll',()=>updateActive(el));restoreMarks(el);updateActive(el)});
 document.querySelectorAll('.round-link').forEach(b=>{const tooltip=b.querySelector('.round-tooltip');const place=()=>{const rect=b.getBoundingClientRect();tooltip.style.left=(rect.right+7)+'px';tooltip.style.top=Math.min(rect.top,window.innerHeight-50)+'px'};b.addEventListener('pointerenter',place);b.addEventListener('focus',place);b.onclick=()=>{const el=document.querySelector(`.messages[data-col="${b.dataset.col}"]`),target=$(`round-${b.dataset.col}-${b.dataset.round}`);el.scrollTo({top:el.scrollTop+target.getBoundingClientRect().top-el.getBoundingClientRect().top-20,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}});
 const ready=cols.every(complete);$('settings').textContent=ready?'✓ 模型配置成功':'模型配置';$('settings').classList.toggle('success',ready);$('settings').disabled=working();$('add').disabled=cols.length>=5||working();$('add').title=cols.length>=5?'最多支持 5 个模型':'添加模型列';$('count').textContent=`${cols.length} / 5 个模型`;$('send').disabled=working();$('new').disabled=working();$('history-open').disabled=working();$('chat-title').textContent=(cols.flatMap(c=>c.history).find(m=>m.role==='user')?.display||'多模型工作台').slice(0,24);$('footer').textContent=`${cols.length} 个模型并行 · ${round?'已进行 '+round+' 轮对话':'独立思考，共同推进'}`;persist();
}
function updateActive(el){const links=el.parentElement.querySelectorAll('.round-link'),sections=[...el.querySelectorAll('.question')];let active=sections[0];for(const s of sections)if(s.getBoundingClientRect().top<=el.getBoundingClientRect().top+85)active=s;links.forEach(b=>b.classList.toggle('active',active?.id===`round-${b.dataset.col}-${b.dataset.round}`));}
function textNodes(el){const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);return nodes}
function paint(el,start,end){let offset=0;for(const node of textNodes(el)){const len=node.textContent.length,a=Math.max(0,start-offset),b=Math.min(len,end-offset);if(b>a){const range=document.createRange();range.setStart(node,a);range.setEnd(node,b);const mark=document.createElement('mark');mark.className='highlight';range.surroundContents(mark)}offset+=len;}}
function restoreMarks(el){const c=cols.find(c=>c.id===+el.dataset.col);el.querySelectorAll('.answer').forEach(a=>(c.history[+a.dataset.message]?.marks||[]).forEach(m=>paint(a,m.start,m.end)));}
$('board').addEventListener('mouseup',()=>{if(!$('highlight').checked)return;const selection=window.getSelection();if(!selection.rangeCount||selection.isCollapsed)return;const range=selection.getRangeAt(0);const el=(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement).closest('.answer');if(!el||!el.contains(range.endContainer)||el.classList.contains('error'))return;const text=selection.toString().trim();if(!text)return;const c=cols.find(c=>c.id===+el.closest('[data-col]').dataset.col),m=c.history[+el.dataset.message];const pre=document.createRange();pre.selectNodeContents(el);pre.setEnd(range.startContainer,range.startOffset);const start=pre.toString().length,end=start+range.toString().length;m.marks??=[];if(m.marks.some(x=>start<x.end&&end>x.start))return;m.marks.push({start,end});paint(el,start,end);quotes.push({id:++uid,text,source:c.provider,model:c.model,col:c.id,round:m.round,message:m});renderQuotes();persist();selection.removeAllRanges();});
function renderQuotes(){$('quotes').innerHTML=quotes.map(q=>`<span class="chip" title="${esc(q.text)}"><b>${esc(q.source)}</b> ${esc(q.text)}<button data-q="${q.id}" aria-label="移除引用">×</button></span>`).join('');$('quote-count').textContent=quotes.length?`${quotes.length} 个片段将随提问发送`:'高亮片段会加入下一轮提问';document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{quotes=quotes.filter(q=>q.id!==+b.dataset.q);renderQuotes();persist()})}
$('provider').innerHTML=Object.keys(providers).map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');
function fillProvider(){const p=providers[$('provider').value];$('endpoint').value=p.url;$('model').value=p.models[0];closeModelMenu();$('model-status').textContent='填写 API Key 后，点击下拉框获取账号可用的在线模型。';$('provider-note').textContent=p.note||'已预填默认接入地址。选择型号并填入 API Key，即可连接。';}
$('provider').onchange=()=>{fillProvider();$('key').value=''};
function loadSlot(){const c=cols[+$('slot').value];$('provider').value=c.provider;fillProvider();$('model').value=c.model;$('endpoint').value=c.endpoint;$('key').value=c.key;$('remove').disabled=cols.length<=1;$('form-error').textContent=''}
function openConfig(i=0){if(working())return;$('slot').innerHTML=cols.map((c,j)=>`<option value="${j}">第 ${j+1} 列 · ${esc(c.provider)}</option>`).join('');$('slot').value=i;loadSlot();$('dialog').showModal()}
$('slot').onchange=loadSlot;$('settings').onclick=()=>openConfig();$('close').onclick=()=>$('dialog').close();
$('save').onclick=()=>{const model=$('model').value.trim(),key=$('key').value.trim(),endpoint=$('endpoint').value.trim().replace(/\/$/,'');let url;try{url=new URL(endpoint)}catch{}if(!model||!key||!url||url.protocol!=='https:'){$('form-error').textContent='请填写模型型号、API Key 和有效的 HTTPS 接入地址。';return}const c=cols[+$('slot').value],provider=$('provider').value;const changed=c.provider!==provider||c.model!==model||c.endpoint!==endpoint;if(changed&&c.history.length){c.history=[];quotes=quotes.filter(q=>q.col!==c.id);renderQuotes()}Object.assign(c,{provider,model,endpoint,key,protocol:providers[provider].protocol||'openai'});$('dialog').close();render()};
$('remove').onclick=()=>{if(cols.length<=1||working())return;const [c]=cols.splice(+$('slot').value,1);quotes=quotes.filter(q=>q.col!==c.id);renderQuotes();$('dialog').close();render()};
$('add').onclick=()=>{if(cols.length>=5||working())return;cols.push(makeCol('OpenAI'));render();openConfig(cols.length-1)};
$('new').onclick=()=>{if(working())return;persist();currentId=newId();cols=cols.map(c=>({...c,id:++uid,history:[],busy:false}));quotes=[];round=0;$('prompt').value='';renderQuotes();render()};
async function send(){const prompt=$('prompt').value.trim();if(!prompt||working())return;const missing=cols.findIndex(c=>!complete(c));if(missing!==-1){openConfig(missing);return}const refs=quotes.map(({text,source,model,col,round})=>({text,source,model,col,round}));const content=prompt+(refs.length?'\n\n请结合以下高亮参考内容继续思考：\n'+refs.map(q=>`【${q.source} / ${q.model} · 第 ${q.round} 轮】\n${q.text}`).join('\n\n'):'');$('prompt').value='';quotes=[];renderQuotes();round++;const currentRound=round;cols.forEach(c=>{c.history.push({role:'user',content,display:prompt,title:prompt.slice(0,42),round:currentRound,refs});c.busy=true});render({latest:true});await Promise.allSettled(cols.map(async c=>{try{const res=await fetch(API_BASE+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:c.endpoint,key:c.key,model:c.model,protocol:c.protocol,messages:c.history.filter(m=>!m.error).map(({role,content})=>({role,content}))})});const data=await res.json();if(!res.ok)throw Error(data.error||'请求失败');const answer=data.choices?.[0]?.message?.content;if(typeof answer!=='string'||!answer.trim())throw Error('模型未返回文本，请检查型号或额度');c.history.push({role:'assistant',content:answer,round:currentRound,marks:[]})}catch(e){c.history.push({role:'assistant',content:'连接失败：'+e.message+'。请检查本列配置后重新发送。',round:currentRound,error:true})}finally{c.busy=false;render({latest:[c.id]})}}));}
$('history-open').onclick=showHistory;$('history-close').onclick=()=>$('history-dialog').close();$('history-search').oninput=renderHistory;$('prompt').addEventListener('input',persist);$('highlight').addEventListener('change',persist);window.addEventListener('pagehide',persist);$('send').onclick=send;$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}});renderQuotes();render({latest:true});


function closeModelMenu(){modelRequest++;$('model-menu').hidden=true;$('model-open').setAttribute('aria-expanded','false');}
function renderModelOptions(){const query=$('model-search').value.trim().toLowerCase();const filtered=onlineModels.filter(m=>(m.id+' '+(m.name||'')).toLowerCase().includes(query));$('model-results').innerHTML=filtered.map(m=>`<button class="model-option" type="button" data-model="${esc(m.id)}"><b>${esc(m.id)}</b>${m.name&&m.name!==m.id?`<small>${esc(m.name)}</small>`:''}</button>`).join('')||'<p class="picker-note">没有匹配的模型，可以手动输入型号。</p>';document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{$('model').value=b.dataset.model;$('model-open').firstChild.textContent=b.dataset.model+' ';closeModelMenu()});}
async function openModelMenu(){if(!$('model-menu').hidden){closeModelMenu();return}$('model-menu').hidden=false;$('model-open').setAttribute('aria-expanded','true');$('model-search').value='';const key=$('key').value.trim(),endpoint=$('endpoint').value.trim();if(!key){$('model-results').innerHTML='<p class="picker-note">请先填写该服务商的 API Key，再点击这里获取模型。</p>';$('model-status').textContent='需要 API Key 才能获取账号可用模型。';return}const request=++modelRequest;$('model-results').innerHTML='<p class="picker-note">正在获取服务商在线模型…</p>';$('model-status').textContent='正在连接模型列表接口…';try{const res=await fetch(API_BASE+'/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint,key,protocol:providers[$('provider').value].protocol||'openai'})});const data=await res.json();if(request!==modelRequest)return;if(!res.ok)throw Error(data.error||'获取失败');onlineModels=data.models||[];renderModelOptions();$('model-status').textContent=`刚刚从服务商获取 ${onlineModels.length} 个模型（按账号权限返回）。`;}catch(e){if(request!==modelRequest)return;$('model-results').innerHTML='<p class="picker-note">'+esc(e.message)+'<br>该厂商可能不提供模型列表接口，仍可手动输入型号。</p>';$('model-status').textContent='在线列表暂不可用，保留当前型号，可手动填写。';}}
$('model-open').onclick=openModelMenu;$('model-search').oninput=renderModelOptions;$('key').addEventListener('input',closeModelMenu);$('endpoint').addEventListener('input',closeModelMenu);$('dialog').addEventListener('close',closeModelMenu);
