const providers={
 DeepSeek:{url:'https://api.deepseek.com/v1',models:['deepseek-chat','deepseek-reasoner']},
 '智谱 GLM':{url:'https://open.bigmodel.cn/api/paas/v4',models:['glm-4.5','glm-4.5-air','glm-4-plus']},
 '阿里云 · 千问':{url:'https://dashscope.aliyuncs.com/compatible-mode/v1',models:['qwen-plus','qwen-max','qwen-turbo','qwen3-max']},
 OpenAI:{url:'https://api.openai.com/v1',models:['gpt-4.1','gpt-4.1-mini','o3','o4-mini']},
 'Anthropic · Claude':{url:'https://api.anthropic.com/v1',models:['claude-sonnet-4-5','claude-opus-4-1'],protocol:'anthropic'},
 'Google · Gemini':{url:'https://generativelanguage.googleapis.com/v1beta/openai',models:['gemini-2.5-pro','gemini-2.5-flash']},
 '月之暗面 · Kimi':{url:'https://api.moonshot.cn/v1',models:['kimi-k2-0905-preview','moonshot-v1-128k']},
 '字节跳动 · 豆包':{url:'https://ark.cn-beijing.volces.com/api/v3',models:['doubao-seed-1-6-250615'],note:'也可填入火山引擎控制台的推理接入点 ID（ep-…）。'},
 MiniMax:{url:'https://api.minimax.io/v1',models:['MiniMax-M2.7','MiniMax-M2.5']},
 'xAI · Grok':{url:'https://api.x.ai/v1',models:['grok-4','grok-3-mini']},
 Mistral:{url:'https://api.mistral.ai/v1',models:['mistral-large-latest','mistral-small-latest']},
 '硅基流动':{url:'https://api.siliconflow.cn/v1',models:['deepseek-ai/DeepSeek-V3','Qwen/Qwen3-235B-A22B']},
 OpenRouter:{url:'https://openrouter.ai/api/v1',models:['anthropic/claude-sonnet-4.5','google/gemini-2.5-pro','deepseek/deepseek-chat']},
 Groq:{url:'https://api.groq.com/openai/v1',models:['llama-3.3-70b-versatile','openai/gpt-oss-120b']},
 'Together AI':{url:'https://api.together.xyz/v1',models:['meta-llama/Llama-3.3-70B-Instruct-Turbo']},
 '自定义服务':{url:'',models:[''],note:'支持 OpenAI 兼容的 Chat Completions 接口。'}
};
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let uid=0,round=0,quotes=[];function makeCol(p){return {id:++uid,provider:p,model:providers[p].models[0],endpoint:providers[p].url,protocol:providers[p].protocol||'openai',key:'',history:[],busy:false}}
let cols=['DeepSeek','智谱 GLM','阿里云 · 千问'].map(makeCol);
const complete=c=>!!(c.key&&c.model&&c.endpoint),working=()=>cols.some(c=>c.busy);
function markdown(text){return DOMPurify.sanitize(marked.parse(text,{gfm:true,breaks:true}),{ALLOWED_TAGS:['p','br','h1','h2','h3','h4','h5','h6','strong','em','del','s','ul','ol','li','blockquote','pre','code','table','thead','tbody','tr','th','td','hr','a'],ALLOWED_ATTR:['href','title','start']});}
function render({bottom=false}={}){
 const positions=new Map([...document.querySelectorAll('.messages')].map(el=>[+el.dataset.col,el.scrollTop]));
 $('board').style.gridTemplateColumns=`repeat(${cols.length},minmax(260px,1fr))`;
 $('board').innerHTML=cols.map((c,i)=>{
 const rounds=c.history.filter(m=>m.role==='user');return `<article class="column" data-id="${c.id}"><div class="colhead"><div class="model"><span class="icon color${i%5}">${['D','G','Q','A','M'][i%5]}</span><div><strong>${esc(c.provider)}</strong><div class="model-sub">${esc(c.model||'选择型号')}</div></div></div><button class="iconbtn config" data-i="${i}" title="修改本列模型" aria-label="修改第 ${i+1} 列模型">⌘</button></div><div class="col-status"><span class="dot ${complete(c)?'ready':''}"></span>${c.busy?'正在生成回答…':complete(c)?'模型配置成功':'尚未连接'}<span>${rounds.length} 轮对话</span></div><div class="conversation"><nav class="roundnav" aria-label="${esc(c.provider)} 轮次导航"><div class="navscroll">${rounds.map(m=>`<button class="round-link" data-col="${c.id}" data-round="${m.round}" aria-label="第 ${m.round} 轮：${esc(m.title)}"><i></i><span class="round-tooltip">第 ${m.round} 轮 · ${esc(m.title)}</span></button>`).join('')}</div></nav><div class="messages" data-col="${c.id}">${c.history.length?c.history.map((m,j)=>`<section class="msg ${m.role==='user'?'question':'response'}" ${m.role==='user'?`id="round-${c.id}-${m.round}"`:''}><div class="label">${m.role==='user'?`<span>你</span><small>第 ${m.round} 轮</small>`:`<span>${esc(c.provider)}</span><small>${m.error?'请求未完成':'回答'}</small>`}</div><div class="${m.role==='user'?'user':'answer markdown'} ${m.error?'error':''}" data-message="${j}">${m.role==='user'?esc(m.display||m.content):m.error?esc(m.content):markdown(m.content)}</div>${m.refs?.length?`<details class="ref-detail"><summary>引用 ${m.refs.length} 个高亮片段</summary>${m.refs.map(q=>`<p><b>${esc(q.source)}</b> ${esc(q.text)}</p>`).join('')}</details>`:''}</section>`).join('')+(c.busy?'<div class="thinking"><i></i><i></i><i></i><span>模型正在思考</span></div>':''):`<div class="empty"><div class="empty-symbol">✳</div><strong>${complete(c)?'准备好，开始思考':'连接你的模型'}</strong><p>${complete(c)?'在下方提出问题，<br>让不同模型一起寻找答案。':'选择你喜欢的模型，填入 API Key。<br>同一个问题，获得独立的思考。'}</p>${complete(c)?'<span class="connected-pill">✓ 模型配置成功</span>':`<button class="btn config" data-i="${i}">配置本列模型 <span>↗</span></button>`}</div>`}</div></div></article>`;
 }).join('');
 document.querySelectorAll('.config').forEach(b=>{b.disabled=working();b.onclick=()=>openConfig(+b.dataset.i)});
 document.querySelectorAll('.messages').forEach(el=>{el.scrollTop=(bottom===true||(Array.isArray(bottom)&&bottom.includes(+el.dataset.col)))?el.scrollHeight:(positions.get(+el.dataset.col)||0);el.addEventListener('scroll',()=>updateActive(el));restoreMarks(el);updateActive(el)});
 document.querySelectorAll('.round-link').forEach(b=>{const tooltip=b.querySelector('.round-tooltip');const place=()=>{const rect=b.getBoundingClientRect();tooltip.style.left=(rect.right+7)+'px';tooltip.style.top=Math.min(rect.top,window.innerHeight-50)+'px'};b.addEventListener('pointerenter',place);b.addEventListener('focus',place);b.onclick=()=>{const el=document.querySelector(`.messages[data-col="${b.dataset.col}"]`),target=$(`round-${b.dataset.col}-${b.dataset.round}`);el.scrollTo({top:el.scrollTop+target.getBoundingClientRect().top-el.getBoundingClientRect().top-20,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}});
 const ready=cols.every(complete);$('settings').textContent=ready?'✓ 模型配置成功':'模型配置';$('settings').classList.toggle('success',ready);$('settings').disabled=working();$('add').disabled=cols.length>=5||working();$('add').title=cols.length>=5?'最多支持 5 个模型':'添加模型列';$('count').textContent=`${cols.length} / 5 个模型`;$('send').disabled=working();$('new').disabled=working();$('footer').textContent=`${cols.length} 个模型并行 · ${round?'已进行 '+round+' 轮对话':'独立思考，共同推进'}`;
}
function updateActive(el){const links=el.parentElement.querySelectorAll('.round-link'),sections=[...el.querySelectorAll('.question')];let active=sections[0];for(const s of sections)if(s.getBoundingClientRect().top<=el.getBoundingClientRect().top+85)active=s;links.forEach(b=>b.classList.toggle('active',active?.id===`round-${b.dataset.col}-${b.dataset.round}`));}
function textNodes(el){const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);return nodes}
function paint(el,start,end){let offset=0;for(const node of textNodes(el)){const len=node.textContent.length,a=Math.max(0,start-offset),b=Math.min(len,end-offset);if(b>a){const range=document.createRange();range.setStart(node,a);range.setEnd(node,b);const mark=document.createElement('mark');mark.className='highlight';range.surroundContents(mark)}offset+=len;}}
function restoreMarks(el){const c=cols.find(c=>c.id===+el.dataset.col);el.querySelectorAll('.answer').forEach(a=>(c.history[+a.dataset.message]?.marks||[]).forEach(m=>paint(a,m.start,m.end)));}
$('board').addEventListener('mouseup',()=>{if(!$('highlight').checked)return;const selection=window.getSelection();if(!selection.rangeCount||selection.isCollapsed)return;const range=selection.getRangeAt(0);const el=(range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement).closest('.answer');if(!el||!el.contains(range.endContainer)||el.classList.contains('error'))return;const text=selection.toString().trim();if(!text)return;const c=cols.find(c=>c.id===+el.closest('[data-col]').dataset.col),m=c.history[+el.dataset.message];const pre=document.createRange();pre.selectNodeContents(el);pre.setEnd(range.startContainer,range.startOffset);const start=pre.toString().length,end=start+range.toString().length;m.marks??=[];if(m.marks.some(x=>start<x.end&&end>x.start))return;m.marks.push({start,end});paint(el,start,end);quotes.push({id:++uid,text,source:c.provider,model:c.model,col:c.id,round:m.round,message:m});renderQuotes();selection.removeAllRanges();});
function renderQuotes(){$('quotes').innerHTML=quotes.map(q=>`<span class="chip" title="${esc(q.text)}"><b>${esc(q.source)}</b> ${esc(q.text)}<button data-q="${q.id}" aria-label="移除引用">×</button></span>`).join('');$('quote-count').textContent=quotes.length?`${quotes.length} 个片段将随提问发送`:'高亮片段会加入下一轮提问';document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{quotes=quotes.filter(q=>q.id!==+b.dataset.q);renderQuotes()})}
$('provider').innerHTML=Object.keys(providers).map(p=>`<option>${esc(p)}</option>`).join('');
function fillProvider(){const p=providers[$('provider').value];$('endpoint').value=p.url;$('model').value=p.models[0];$('models').innerHTML=p.models.map(m=>`<option value="${esc(m)}">`).join('');$('provider-note').textContent=p.note||'已预填默认接入地址。选择型号并填入 API Key，即可连接。';}
$('provider').onchange=()=>{fillProvider();$('key').value=''};
function loadSlot(){const c=cols[+$('slot').value];$('provider').value=c.provider;fillProvider();$('model').value=c.model;$('endpoint').value=c.endpoint;$('key').value=c.key;$('remove').disabled=cols.length<=1;$('form-error').textContent=''}
function openConfig(i=0){if(working())return;$('slot').innerHTML=cols.map((c,j)=>`<option value="${j}">第 ${j+1} 列 · ${esc(c.provider)}</option>`).join('');$('slot').value=i;loadSlot();$('dialog').showModal()}
$('slot').onchange=loadSlot;$('settings').onclick=()=>openConfig();$('close').onclick=()=>$('dialog').close();
$('save').onclick=()=>{const model=$('model').value.trim(),key=$('key').value.trim(),endpoint=$('endpoint').value.trim().replace(/\/$/,'');let url;try{url=new URL(endpoint)}catch{}if(!model||!key||!url||url.protocol!=='https:'){$('form-error').textContent='请填写模型型号、API Key 和有效的 HTTPS 接入地址。';return}const c=cols[+$('slot').value],provider=$('provider').value;const changed=c.provider!==provider||c.model!==model||c.endpoint!==endpoint;if(changed&&c.history.length){c.history=[];quotes=quotes.filter(q=>q.col!==c.id);renderQuotes()}Object.assign(c,{provider,model,endpoint,key,protocol:providers[provider].protocol||'openai'});$('dialog').close();render()};
$('remove').onclick=()=>{if(cols.length<=1||working())return;const [c]=cols.splice(+$('slot').value,1);quotes=quotes.filter(q=>q.col!==c.id);renderQuotes();$('dialog').close();render()};
$('add').onclick=()=>{if(cols.length>=5||working())return;cols.push(makeCol('OpenAI'));render();openConfig(cols.length-1)};
$('new').onclick=()=>{if(working())return;cols.forEach(c=>c.history=[]);quotes=[];round=0;renderQuotes();render()};
async function send(){const prompt=$('prompt').value.trim();if(!prompt||working())return;const missing=cols.findIndex(c=>!complete(c));if(missing!==-1){openConfig(missing);return}const refs=quotes.map(({text,source,model,col,round})=>({text,source,model,col,round}));const content=prompt+(refs.length?'\n\n请结合以下高亮参考内容继续思考：\n'+refs.map(q=>`【${q.source} / ${q.model} · 第 ${q.round} 轮】\n${q.text}`).join('\n\n'):'');$('prompt').value='';quotes=[];renderQuotes();round++;const currentRound=round;cols.forEach(c=>{c.history.push({role:'user',content,display:prompt,title:prompt.slice(0,42),round:currentRound,refs});c.busy=true});render({bottom:true});await Promise.allSettled(cols.map(async c=>{try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:c.endpoint,key:c.key,model:c.model,protocol:c.protocol,messages:c.history.filter(m=>!m.error).map(({role,content})=>({role,content}))})});const data=await res.json();if(!res.ok)throw Error(data.error||'请求失败');const answer=data.choices?.[0]?.message?.content;if(typeof answer!=='string'||!answer.trim())throw Error('模型未返回文本，请检查型号或额度');c.history.push({role:'assistant',content:answer,round:currentRound,marks:[]})}catch(e){c.history.push({role:'assistant',content:'连接失败：'+e.message+'。请检查本列配置后重新发送。',round:currentRound,error:true})}finally{const el=document.querySelector(`.messages[data-col="${c.id}"]`);const nearBottom=el&&el.scrollHeight-el.scrollTop-el.clientHeight<80;c.busy=false;render({bottom:nearBottom?[c.id]:[]})}}));}
$('send').onclick=send;$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}});renderQuotes();render();
